import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { buildCatalog } from "../src/lib/price-rules.js";
import { games as gameMaster } from "../src/data/games.js";

const root = resolve(import.meta.dirname, "..");
const raw = JSON.parse(await readFile(resolve(root, "data/source-offers.json"), "utf8"));
const catalog = buildCatalog(raw.offers, raw.updatedAt, gameMaster);

const output = `// Generated by scripts/build-catalog.mjs. Do not edit manually.\nexport const catalogUpdatedAt = ${JSON.stringify(raw.updatedAt)};\nexport const generatedGames = ${JSON.stringify(catalog, null, 2)};\n`;
await writeFile(resolve(root, "src/data/generated-catalog.js"), output, "utf8");
console.log(`Generated ${catalog.length} catalog records from ${raw.offers.length} source offers.`);
